#use_frameworks!

platform :ios, '8.0'

target 'OMTFoundation_Example' do
  pod 'OMTFoundation', :path => '../'
  pod 'AFNetworking'
  target 'OMTFoundation_Tests' do
    inherit! :search_paths

    
  end
end
